### ISSUE TITLE
Move this repo into the CSS Recipes org

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-config-cssrecipes#12]
@magsout We're freeing up the stylelint org to focus on stylelint as a tool rather than the configs. As such we are moving the SuitCSS, Wordpress, CSS Recipes and Standard configs out of the org. We've [just finished](https://github.com/suitcss/stylelint-config-suitcss/issues/5) transferring the SuitCSS config to the SuitCSS org. I thought the [CSS Recipes](https://github.com/cssrecipes) would make a good home for this repo as you're using it to check the style of the components. What do you think?

**Comment by MoOx** [comment]
Done :)

**Comment by jeddy3** [comment]
Thanks @MoOx! Much appreciated :)
