### ISSUE TITLE
Doesn't work with gulp-postcss

### ISSUE THREAD

**Issue by TrySound** [stylelint/stylelint-config-cssrecipes#8]
``` js
[01:58:05] TypeError in plugin 'gulp-postcss'
Message:
    Object.keys called on non-object
```

With standard config everything fine. Maybe some rules somehow break warnings?

**Comment by jeddy3** [comment]
I can't seem to replicate this. No warnings with `stylelint-config-cssrecipes@2.0.0`, `gulp-postcss@6.0.1` and `gulp@3.9.0`. 

My `gulpfile` is this:

``` js
var postcss = require('gulp-postcss');
var gulp = require('gulp');
var stylelint = require('stylelint');

gulp.task('default', function () {
    var processors = [stylelint()];
    return gulp.src('css/temp.css')
        .pipe(postcss(processors));
});
```

And the config specified in the `package.json`:

``` json
{
  "stylelint": {
    "extends": "stylelint-config-cssrecipes"
  }
}
```

Can you please paste your `gulpfile` here so we can try to get to the bottom of this? :)

**Comment by MoOx** [comment]
And what version are you using @TrySound ?

**Comment by TrySound** [comment]
Seems like the problem since indentation rule in postcssPlugin.js

``` js
indentation: [ 2, 2, { hierarchicalSelectors: true } ]
```

**Comment by TrySound** [comment]
Here is number
https://github.com/stylelint/stylelint/blob/master/src/utils/validateOptions.js#L54

**Comment by TrySound** [comment]
Yep. Actual is not checked. Only possible.

**Comment by TrySound** [comment]
This works fine.

``` js
indentation: 2
```

**Comment by TrySound** [comment]
Oh, I understand. It can't validate old syntax. But should.

**Comment by TrySound** [comment]
Think we should also check the second element here
https://github.com/stylelint/stylelint/blob/master/src/postcssPlugin.js#L64
